### PR TITLE
Fix an issue where a player was able to join a game, never write a message and thus being almost unbannable

### PR DESCRIPTION
**Pull request by Olfi01**
Like, for example, if that person had an arab name and those weren't allowed in that one specific group

### CODE REVIEW

**Comment by Olfi01** [comment]
AAAAND im an idiot. Imma revert the changes made for the other PR -.-

**Comment by Olfi01** [comment]
DONE.

**Comment by renyhp** [comment]
Eeeeeh just for this little change would you be so kind to close this one and make another PR with only one commit?

**Comment by Olfi01** [comment]
Haha OFC im sorry, gonna do it soon

**Comment by Olfi01** [comment]
done.

**Pull request closed without merging**
