### PR TITLE
Added a missing space xP

### PR DESCRIPTION
**Pull request by Olfi01**
There was a space missing that really annoyed us translators... so i added it.

### CODE REVIEW

**Comment by Olfi01** [comment]
Oh, and the thing with that string... it now should be something like
<string key="HunterShotWolf">
    <!— 0 - target's name —>
    <value>The wolf tried to attack the hunter last night, but the hunter was able to take them down with their rifle!</value>
<!--PlayerRoleWas following>
</string>

**Comment by Olfi01** [comment]
please tell me if i misunderstood something inside the code btw

**Comment by renyhp** [comment]
I can't understand how the string should change, and why...
Besides, probably you mean `p.GetName()` with capital G :P

**Comment by Olfi01** [comment]
Well basically there's that problem that a new sentence starts with a lowercase letter, because it just uses {role} is dead, while {role} is the same as in {name} was {role}. That is a problem because the werewolf {role} is "a Werewolf" and thus it can't be at the beginning of a sentence. So the easiest way to fix it would be to append the PlayerRoleWas string instead of putting the role inside the HunterShotWolf Message.

**Comment by Olfi01** [comment]
Oh, and it's easier to understand if the PlayerRoleWas String is used instead. Paula was really confused about that.

**Comment by renyhp** [comment]
Sure, you're right, but there's no need to change the string. You already append PlayerRoleWas in the code

**Comment by Olfi01** [comment]
But if it stays like this, it will say something like: 
The wolf tried to attack the hunter last night, but the hunter was able to take {role} down with their rifle! {player} was {role}.
The role would be told two times. And rn it is like:
The wolves tried to attack the hunter last night, but the hunter was able to take one down with them as he died! ham has died (wolf)a Werewolf 🐺 is dead

**Comment by Olfi01** [comment]
Do you get my point?

**Comment by renyhp** [comment]
HunterShotWolfMulti is
`The wolves tried to attack the hunter last night, but the hunter was able to take one down with them as he died! {0} has died (wolf)`

HunterShotWolf is
`The wolf tried to attack the hunter last night, but the hunter was able to take the wolf {0} down with their rifle!`

The argument {0} is always the name of the player, as you can see in the code (`GetLocaleString(voteWolvesCount > 1 ? "HunterShotWolfMulti" : "HunterShotWolf", p.GetName())`). So appending `" " + {0} was {1}` where {0} = player name and {1} = player role won't make anything repeat

**Comment by Olfi01** [comment]
Oh yes sorry 😂 please don't mind my mind. It's confused. Yes, we don't need to change a string, just merging this pull request would do. 
(I see an idiot. In front of me, there is a mirror.)

**Pull request merged**
